build:
  environment:
    timezone: UTC
    # https://scrutinizer-ci.com/docs/build/languages
    hosts:
      local.dev: '127.0.0.1'
    variables:
      PHP_VERSION: 8.1
  dependencies:
    before:
      - composer install
  postgresql: false
  mysql: 5.5
  apache2:
    modules: [ 'rewrite', 'expires', 'ssl', 'macro', 'headers' ]
    sites:
      alxarafe:
        host: 'local.dev'
        web_root: ''
  tests:
    override:
      - phpunit --coverage-clover=coverage.clover
filter:
  paths:
    - src/*

tools:
  php_analyzer: true
  external_code_coverage:
    enabled: false
    timeout: 600
    filter:
      excluded_paths:
        - 'vendor/*'

coding_style:
  php:
    indentation:
      general:
        use_tabs: false
        size: 4
      switch:
        indent_case: true
    spaces:
      around_operators:
        concatenation: true
