filter:
  paths:
    - src/*

tools:
  php_analyzer: true
  external_code_coverage: true

build:
  environment:
    php: 8.1
  dependencies:
    before:
      - composer install
  tests:
    override:
      - phpunit --coverage-clover=coverage.clover

coding_style:
  checks:
    php:
      code_rating: true
      php_style:
        disabled: false
      syntax_error:
        disabled: false
      unused_variables: true

repository:
  exclusions:
    - "tests/*"
