build:
  environment:
    variables:
      PHP_VERSION: 8.1
  dependencies:
    before:
      - composer install
  tests:
    override:
      - phpunit --coverage-clover=coverage.clover
filter:
  paths:
    - src/*

tools:
  php_analyzer: true
  external_code_coverage:
    enabled: false
    timeout: 600
    filter:
      excluded_paths:
        - 'vendor/*'

coding_style:
  php:
    indentation:
      general:
        use_tabs: false
        size: 4
      switch:
        indent_case: true
    spaces:
      around_operators:
        concatenation: true
