filter:
  paths:
    - src/*

tools:
  php_analyzer: true
  external_code_coverage: true

build:
  environment:
    php: 8.1
  dependencies:
    before:
      - composer install
  tests:
    override:
      - phpunit --coverage-clover=coverage.clover

coding_style:
  php:
    spaces:
      around_operators: true
      before_keywords: false
      before_left_brace: true
      before_parentheses: false
      within:
        parentheses: false
        brackets: false
        array_initializers: false
    braces:
      classes_function: new-line
    conventions:
      visibility: true
      private: true
      protected: true
    ordering:
      use_statements: alpha
      within_class: alpha

repository:
  exclusions:
    - "tests/*"